### ISSUE TITLE
Episode title parsed as release group name

### ISSUE THREAD

**Issue by rzumer** [erengy/anitomy#13]
I have a sample formatted in this way (substitutions are surrounded by curly brackets):
`[{Category}] -{Romanized Title}- {Original Title} Vol{Volume Number} 第{Episode Number}話 「{Episode Title}」 ({Video Codec} {WxH Resolution} {Audio Codec}).{Extension}`

In this situation the episode title is parsed as the release group name and displayed as such in Taiga.

I know enclosing titles within brackets goes against your suggestions in the readme, but I have never seen Japanese brackets (「」) used for group names. Perhaps introducing bias for this pattern could be a solution?

**Comment by erengy** [comment]
Anitomy is now able to parse episode titles in `「」`.

The closest example I could find in that format was `[POPGO] Mobile Suit Gundam The Witch from Mercury 機動戦士ガンダム 水星の魔女 第01話 「魔女と花嫁」 Webrip 1080p HEVC`, so I used that as a test case:

```
┌───────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Element          │ Value                                                                              │
│───────────────────────────────────────────────────────────────────────────────────────────────────────│
│ release_group    │ POPGO                                                                              │
│ title            │ Mobile Suit Gundam The Witch from Mercury 機動戦士ガンダム 水星の魔女              │
│ episode          │ 01                                                                                 │
│ episode_title    │ 魔女と花嫁                                                                         │
│ source           │ Webrip                                                                             │
│ video_resolution │ 1080p                                                                              │
│ video_term       │ HEVC                                                                               │
└───────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

If you still have the original filename without the substitutions, let me know and I'll add that as another test case.
