### ISSUE TITLE
Group tag being parsed as episode number

### ISSUE THREAD

**Issue by menma1234** [erengy/anitomy#14]
`[0x539] Somali and the Forest Spirit - S01E01 (WEB 1080p Hi10P AAC) [BB7C6531].mkv` is being parsed as "Somali and the Forest Spirit - S01E01" episode 539 in Taiga.

**Comment by jasonsparc** [comment]
Same problem here. I wish they didn't name their group "0x539" though :v

**Comment by ThaUnknown** [comment]
same problem with kobayashis dragon maid
