### ISSUE TITLE
Anime Title Inconsistent Parsing Given Anime Type

### ISSUE THREAD

**Issue by Jaliborc** [erengy/anitomy#15]
I was running some tests (https://runkit.com/jaliborc/5c13d05e6ba83b0012bfbcf2) and I noticed this issue with the parser: if you look at the last two tests, you see that `Piano no Mori 2 (TV)` gives the anime_title `Piano no Mori`, with season `2` and anime_type `TV`. But `Piano no Mori (TV) 2nd Season` gives anime_title `Piano no Mori (TV)`, with the anime_type `TV` remaining the same.

**Comment by erengy** [comment]
This behavior is now changed in the development branch. Both cases return `Piano no Mori` as the title:

```
┌─────────────────────────┐
│ Element │ Value         │
│─────────────────────────│
│ title   │ Piano no Mori │
│ episode │ 2             │
│ type    │ TV            │
└─────────────────────────┘
```

```
┌─────────────────────────┐
│ Element │ Value         │
│─────────────────────────│
│ title   │ Piano no Mori │
│ type    │ TV            │
│ season  │ 2             │
└─────────────────────────┘
```
