### ISSUE TITLE
How Do I Use It

### ISSUE THREAD

**Issue by RavenZReal** [erengy/anitomy#16]
i am using taiga but when i finished haikyuu seasons 1 and when i played the first ep of season 2 it kept saying playing haikyu first season first ep (i use anichiraku its a gdrive of anime and i cant edit the name)

**Comment by erengy** [comment]
Hey, sorry for the late reply. I'm closing this issue since it's most likely related to Taiga rather than Anitomy. But if you're having similar problems with other files, let me know their names and I'll take a look. Cheers.
