### ISSUE TITLE
Compilation error: back_inserter is not a member of std

### ISSUE THREAD

**Issue by AsukaLangleyfag** [erengy/anitomy#2]
Tried to compile taiga with Visual Studio 2015 RTM, while compilation of anitomy got an error in line 182 of tokenizer.cpp:
Error C2039: 'back_inserter': is not a member of 'std'
Error C3861: 'back_inserter': identifier not found

**Comment by erengy** [comment]
It might work if you include the `<iterator>` header in `tokenizer.cpp`, as in:

```cpp
#include <algorithm>
#include <iterator>
#include <set>
```

Could you try that out? I haven't switched to VS 2015 yet.

**Comment by AsukaLangleyfag** [comment]
Yup, looks like it compiles now. But I got an another issue, now with Taiga.
