### ISSUE TITLE
New keyword "WEB"

### ISSUE THREAD

**Issue by moonlight83340** [erengy/anitomy#22]
Sometime anime have different pattern with the WEB keyword :
Kubo.Wont.Let.Me.Be.Invisible.S01E12.VOSTFR.1080p.WEB.x264-TsundereRaws-Wawacity.cyou
Seems to mean WEBRIP I guess.
I don't know if it's really matters.

**Comment by erengy** [comment]
Added in f617f8400d301949093a077cfc13b25b5c5c3a8e.
