### ISSUE TITLE
Consider License Change to LGPL

### ISSUE THREAD

**Issue by ubercow** [erengy/anitomy#5]
Hello,
I would like to use this library in a project I have, but I am unable to do so because of the GPL license. The GPL license requires that if I include it in my project, even as a linked library, I must also license my code under GPL. As this is a private project I am unable to publish the code as required.

Would you please consider switching to a license such as LGPL? This permits linking to private projects while still encouraging contribution to the library. A copy of LGPL can be found [here](http://choosealicense.com/licenses/lgpl-3.0/).

It appears you don't mind this, as "MAL Updater OSX" and "Hachidori" are both released under BSD 3-Clause license and are technically in violation of the terms you have grated them.

There has been a lot of great work done on this project around parsing edge cases in titles and I would really like to take advantage of that without having to start from scratch in my own project.

Thanks,
Zak Kristjanson

**Comment by erengy** [comment]
Hey there Zak,

Someone else has just recently made a similar request, and I agree that the library should be available under a more permissive license. I was actually planning to open an issue here myself.

I think I'd like to keep the copyleft requirement, so it seems the main options that I have are [LGPL 3.0](http://choosealicense.com/licenses/lgpl-3.0/) and [MPL 2.0](http://choosealicense.com/licenses/mpl-2.0/). I'm going to need some time to be able to look into how they handle static linking, though. Any help would be appreciated.

**Comment by ubercow** [comment]
Poking around GNU's site for info for their [FAQ](http://www.gnu.org/licenses/gpl-faq.en.html#LGPLStaticVsDynamic) and found this tidbit about static linking

>For the purpose of complying with the LGPL (any extant version: v2, v2.1 or v3):
>
>(1) If you statically link against an LGPL'd library, you must also provide your application in an object (not necessarily source) format, so that a user has the opportunity to modify the library and relink the application.
>
>(2) If you dynamically link against an LGPL'd library already present on the user's computer, you need not convey the library's source. On the other hand, if you yourself convey the executable LGPL'd library along with your application, whether linked with statically or dynamically, you must also convey the library's sources, in one of the ways for which the LGPL provides.

Here's also a snip from a [Hacker News comment](https://news.ycombinator.com/item?id=5141029) about libgit2, which is GPL with an explicit linking exception, instead of LGPL

>Apparently libgit2, which they're using for this has the license: libgit2 is under GPL2 with linking exemption. This means you can link to the library with any program, commercial, open source or other. However, you cannot modify libgit2 and distribute it without supplying the source.
That sounds nice to me, but I'm not sure how that differs from the standard LGPLv2.

>LGPL requires that any distribution be able to replace the LGPL component with a modified version. If you use it as a shared library (er, DLL in this case I guess) you get that for free. But if, for example, you want to link a LGPL library statically you need to provide a static library containing the rest of your program in a linkable form.
>The point is to allow the user the ability to exercise their right to modify the LGPL library and use it. The license you describe would presumably allow Microsoft to ship a binary with a fixed and unchangable libgit2 implementation.


My friend @kepstin, who understands this stuff way better than I do:

>the lgpl linker exception is explicitly to allow an application with non-gpl-compatible license (e.g. proprietary or has additional restrictions) to be distributed together with or linking to gpl code without having to be relicensed

>basically, switching from GPL to LGPL is saying "I'm ok with proprietary (no source available/usable) code using my library
which might be ok with him
gnu propaganda recommends against it, since they want people to use gpl to leverage others into releasing code in gpl or gpl-compatible licenses

From the [MPL 2.0 FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/):

>Q11: How 'viral' is the MPL? If I use MPL-licensed code in my proprietary application, will I have to give all the source code away?

>No. The license requires that Modifications (as defined in Section 1.10 of the license) must be licensed under the MPL and made available to anyone to whom you distribute the Source Code. However, new files containing no MPL-licensed code are not Modifications, and therefore do not need to be distributed under the terms of the MPL, even if you create a Larger Work (as defined in Section 1.7) by using, compiling, or distributing the non-MPL files together with MPL-licensed files. This allows, for example, programs using MPL-licensed code to be statically linked to and distributed as part of a larger proprietary piece of software, which would not generally be possible under the terms of stronger copyleft licenses.

Not sure exactly what you're looking for in terms of static linking restrictions/permissions, but this might be a good starting point for you.

**Comment by Diablofan** [comment]
Basically statically linking anitomy into taiga is perfectly fine/compatible by gpl and lgpl. Since you have to release taigas source anyway (because of the  gpl) then statically linking anitomy would be fine as well if it were lgpl since you'd have to release it because of the gpl anyway as I understand, however im no lawyer so don't quote me on that.


Sent from Outlook Mobile






On Fri, Feb 26, 2016 at 2:51 PM -0800, "Zak Kristjanson" <notifications@github.com> wrote:





Poking around GNU's site for info for their [FAQ](http://www.gnu.org/licenses/gpl-faq.en.html#LGPLStaticVsDynamic) and found this tidbit about static linking

>For the purpose of complying with the LGPL (any extant version: v2, v2.1 or v3):
>
>(1) If you statically link against an LGPL'd library, you must also provide your application in an object (not necessarily source) format, so that a user has the opportunity to modify the library and relink the application.
>
>(2) If you dynamically link against an LGPL'd library already present on the user's computer, you need not convey the library's source. On the other hand, if you yourself convey the executable LGPL'd library along with your application, whether linked with statically or dynamically, you must also convey the library's sources, in one of the ways for which the LGPL provides.

Here's also a snip from a [Hacker News comment](https://news.ycombinator.com/item?id=5141029) about libgit2, which is GPL with an explicit linking exception, instead of LGPL

>Apparently libgit2, which they're using for this has the license: libgit2 is under GPL2 with linking exemption. This means you can link to the library with any program, commercial, open source or other. However, you cannot modify libgit2 and distribute it without supplying the source.
That sounds nice to me, but I'm not sure how that differs from the standard LGPLv2.

>LGPL requires that any distribution be able to replace the LGPL component with a modified version. If you use it as a shared library (er, DLL in this case I guess) you get that for free. But if, for example, you want to link a LGPL library statically you need to provide a static library containing the rest of your program in a linkable form.
>The point is to allow the user the ability to exercise their right to modify the LGPL library and use it. The license you describe would presumably allow Microsoft to ship a binary with a fixed and unchangable libgit2 implementation.


My friend @kepstin, who understands this stuff way better than I do:

>the lgpl linker exception is explicitly to allow an application with non-gpl-compatible license (e.g. proprietary or has additional restrictions) to be distributed together with or linking to gpl code without having to be relicensed

>basically, switching from GPL to LGPL is saying "I'm ok with proprietary (no source available/usable) code using my library
which might be ok with him
gnu propaganda recommends against it, since they want people to use gpl to leverage others into releasing code in gpl or gpl-compatible licenses

From the [MPL 2.0 FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/):

>Q11: How 'viral' is the MPL? If I use MPL-licensed code in my proprietary application, will I have to give all the source code away?

>No. The license requires that Modifications (as defined in Section 1.10 of the license) must be licensed under the MPL and made available to anyone to whom you distribute the Source Code. However, new files containing no MPL-licensed code are not Modifications, and therefore do not need to be distributed under the terms of the MPL, even if you create a Larger Work (as defined in Section 1.7) by using, compiling, or distributing the non-MPL files together with MPL-licensed files. This allows, for example, programs using MPL-licensed code to be statically linked to and distributed as part of a larger proprietary piece of software, which would not generally be possible under the terms of stronger copyleft licenses.

Not sure exactly what you're looking for in terms of static linking restrictions/permissions, but this might be a good starting point for you.

---

**Comment by erengy** [comment]
> statically linking anitomy into taiga is perfectly fine/compatible

Well, *I* can do absolutely anything I want, since I'm the author of both Anitomy and Taiga anyway.   :stuck_out_tongue:

> im no lawyer so don't quote me on that.

Done!

---

Not sure if I missed anything, but here's an outline of what I'd like to have in the license:

- You are allowed to use the library in any project for any purpose, including commercial and proprietary projects.
- You are allowed to include the source files directly into your project (i.e. it doesn't need to be a replaceable .dll or something).
- <s>You are not allowed to sell the library itself, with or without modifications.</s> *(I guess this is not necessary due to the following point.)*
- If you're going to modify the source code of the library, you have to make it available under the same license (this doesn't apply to your parent project).
- Please give credit to me in an appropriate place (e.g. About dialog, Readme file, home page, etc.) -- it's motivating.
- Please don't pretend that you wrote the code, even if you made significant changes -- it's unethical.
- There's no warranty, no liability, etc.

**Comment by tofuness** [comment]
I am no lawyer and do not have proper legal training. However, MPL seems to cover most of these points very well.

> You are allowed to use the library in any project for any purpose, including commercial and proprietary projects.

See Section 2.1 in the license [1].

> You are allowed to include the source files directly into your project (i.e. it doesn't need to be a replaceable .dll or something).

See Section 3.3, "Distribution of a Larger Work"

> If you're going to modify the source code of the library, you have to make it available under the same license (this doesn't apply to your parent project).

See Section 3.1, "Distribution of Source Form".
See Section 3.2, "Distribution of Executable Form"
(talks about modifications)

Q11 in the FAQ[2], as @ubercow mentioned, talks about static linking.

> Please give credit to me in an appropriate place (e.g. About dialog, Readme file, home page, etc.) -- it's motivating.

You can include a per-file boilerplate notice and "You may add additional accurate notices of copyright ownership.". Naturally, anyone that uses the code will then have to keep these notices.

> Please don't pretend that you wrote the code, even if you made significant changes -- it's unethical.

See Section 3.4.

> There's no warranty, no liability, etc.

See Section 3.5, 6.0 and 7.0.

1. https://www.mozilla.org/en-US/MPL/2.0/
2. https://www.mozilla.org/en-US/MPL/2.0/FAQ/

**Comment by tofuness** [comment]
Ping @erengy (?)

**Comment by erengy** [comment]
Sorry, I've had a very busy week. I'm going to look into this within a few days.

**Comment by erengy** [comment]
Anitomy is now licensed under Mozilla Public License 2.0.

**Comment by ubercow** [comment]
:confetti_ball:  awesome! thanks @erengy
